# Generated by Django 5.2.5 on 2025-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exact_oauth", "0002_simplified_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exactonlineauthstate",
            name="user",
        ),
        migrations.RemoveField(
            model_name="exactonlinetoken",
            name="user",
        ),
        migrations.AddField(
            model_name="exactonlineauthstate",
            name="session_key",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="exactonlinetoken",
            name="session_key",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
