# Generated by Django 5.2.5 on 2025-08-23 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exact_oauth", "0004_alter_exactonlinetoken_expires_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exactonlinetoken",
            old_name="division",
            new_name="current_division",
        ),
    ]
