# Generated by Django 5.2.5 on 2025-08-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exact_oauth', '0005_rename_division_exactonlinetoken_current_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='exactonlinetoken',
            name='refresh_token_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
